### ISSUE TITLE
comment is also saved in "path to backup directory"

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-local_lpfmigrator#1]
When saving a comment on the details page, the comment is also written to "path to backup directory"
![grafik](https://user-images.githubusercontent.com/22933650/73368991-30e2c000-42b2-11ea-87d0-657b9feb407e.png)

**Comment by rschrenk** [comment]
fixed c292a5e6d18390f38d54555702d6ebe4dc5b02bb
please review
