### ISSUE TITLE
bullet points when changing content on details page

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-local_lpfmigrator#2]
when changing content on the details page, bullet points summarizing the changed fields appear:
![grafik](https://user-images.githubusercontent.com/22933650/73369226-8b7c1c00-42b2-11ea-826b-a195a4b5197b.png)

**Comment by rschrenk** [comment]
fixed c292a5e6d18390f38d54555702d6ebe4dc5b02bb
please review
